language: node_js
node_js:
  - "8"
install:
  - npm install
  - npm run bootstrap
script:
  - npm run lint
  - npm run test
  - npm run test:integration
after_success: npm run cover
notifications:
  webhooks:
    urls:
      - GITTER_WEBHOOK_URL
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
